wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1662955587.999035
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.6
      5: 0.13.3
      8:
      - 5
