wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: huggingface
    huggingface_version: 4.21.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1663000568.470358
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      3:
      - 23
      4: 3.10.6
      5: 0.13.3
      6: 4.21.2
      8:
      - 5
